export const SITE_TITLE = 'Блог №415';
export const MAIN = 'Главная';
export const AUTHORS = 'Авторы';
export const COMMUNITIES = 'Группы';
export const URL = "https://blog.kreosoft.space/api/";
export const PARENT_BLOCK_HEADER = document.querySelector('.hero');
export const PARENT_BLOCK = document.getElementById("app");
export const EMAIL_MASK = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z_-]+$/;
// export const PHONE_NUMBER_MASK = /^\+7\d{3}\d{3}\-\d{2}\-\d{2}/;
export const PHONE_NUMBER_MASK = /^\+7\(\d{3}\)\d{3}\-\d{2}\-\d{2}/;
export const PASSWORD_MASK = /^[a-zA-Z0-9]*$/;
export const CHANGED_COMMENT_MESSAGE = '(изменен)';
export const ANSWER_TEXT = 'Ответить';
export const OPEN_ANSWERS = 'Раскрыть ответы'
export const DELETE_COMMENT_MESSAGE = '[Коментарий удален]';
export const LIKE_RATIO = 1;
export const POST_RATIO = 1.5;